name: Feature Request
description: Suggest an idea for this home assistant integration
labels: enhancement
body:
  - type: textarea
    id: content
    attributes:
      label: Description
      placeholder: "Let me know what do you miss..."
  - type: textarea
    id: logs
    attributes:
      label: List of tags
      placeholder: "Please use the inspect feature of your browser (while using the default waterkotte web client) in order to extract the corresponding TAGs that should be used to previde the requested data - TIA"
      render: shell